### ISSUE TITLE
Deleting contents between brackets with "Automatic brace completion".

### ISSUE THREAD

**Issue by alerchedahl** [emartineau/SelectionWrapper#2]
Selecting all text inside brackets (parenthesis, square, curly, etc..) and pressing delete or backspace will not delete the text. Instead a closing bracket will be appended to the selection.

This might be related to having "Automatic brace completion
" turned on (Options > Text Editor > [language])

![selection_bracket_issue](https://user-images.githubusercontent.com/1098313/66211753-efa02200-e6bc-11e9-8f2e-1d239aaff363.gif)

**Comment by emartineau** [comment]
Thanks for bringing this to my attention! I think I know what's causing this issue, I'll get to it when I find the time.

For now I suggest typing a single letter and then backspacing instead of directly deleting.
