### ISSUE TITLE
Breaks multi-cursor editing

### ISSUE THREAD

**Issue by ite-klass** [emartineau/SelectionWrapper#5]
* Use SHIFT+ALT+Arrow-Down to enter multi-row/multi-cursor edit
* Enter `(` to write a `(`

Expected: It writes a `(` or a `()` on every cursor

Actual: It writes

```
(

)
```

(on every cursor position)

**Comment by emartineau** [comment]
In the most recent version I have disabled multi-cursor wrapping (hopefully). Your example should now work as expected. Please let me know otherwise. Thanks!
