### ISSUE TITLE
Multi-cusor editing does not wrap selections

### ISSUE THREAD

**Issue by ite-klass** [emartineau/SelectionWrapper#6]
For content

```
abstract
abstract
```

* Place cursor after `a`, and enter multi-cursor editing (SHIFT+ALT+Down) to place a second cursor on the second line after the a.
* Use SHIFT+Right to select both `b` characters.
* Type `(`

Expected: both `b` characters are wrapped in parentheses (just like when this is done with a single cursor on a single line)

Actual:
```
a(b
b
)stract
a(b
b
)stract
```

When multi-cursor mode is entered from bottom to top instead the `b` is being replaced:

```
a(stract
a(stract
```

**Comment by emartineau** [comment]
As mentioned in (#5) multi-cursor wrapping is disabled.

Now box selections should be properly supported (which seems to be what this issue is describing).
The output from your example should now be: 

```
a(b)stract
a(b)stract
```

Let me know if this now works as expected. Thanks!
